Month 10/step 1
trashmarket/react-burger pull request #7
Opened 2022-11-21 20:33 UTC by trashmarket

2022-12-01 16:33 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- Пройтись по всем any и типизировать их более строго. Если этот тип для библиотеки, то его можно найти либо в коде, либо в интернете.

Можно лучше:

-  тип TpasswordMessage можно вывести из TExitBody с помощью встроенных функций ts Required<Type> и Readonly<Type> 
- В простых (не обьектах) константах ts сам сможет вывести тип. Так что тут можно его не писать

Что понравилось:

- Круто, что вы типизируете хуки
- Здорово, что типизировали `useState`

Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.

2022-12-01 16:33 UTC, kyzinatra commented on src/components/app/app.tsx
Отлично! Круто, что вы описываете тип `useState`

2022-12-01 16:33 UTC, kyzinatra commented on src/components/burger-list/burger-list.tsx
> +  const bunRef = useRef<HTMLHeadingElement>(null);
Надо исправить: 
Тип any стоит использовать только в самых крайних случаях, когда вы правда ожидатее в качестве тип данных все что угодно. Строку, обьект, число, дату, символ, bigInt, массив.
Стоит пройтись по коду и поудалять все `any` и заменить из на более строгий тип. В данном случае стоит в `useRef` указать какого типа будет поле `ulRef.current`

2022-12-01 16:33 UTC, kyzinatra commented on src/components/li-drag-and-drop/li-drag-and-drop.tsx
>        if (!ref.current) {
По аналогии. `hover` уже типизирован. Если нажать alt + ЛКМ по методу, то можно увидеть, что передается.\
`hover?: (item: DragObject, monitor: DropTargetMonitor<DragObject, DropResult>) => void;`
(Если зайти в типы, то можно увидеть, что DragObject передается в качестве параметка в `useDrop<тут>()`)

2022-12-01 16:33 UTC, kyzinatra commented on src/components/modal/modal.tsx
> +}
По аналогии. Стоит использовать `FC<PropsWithChildren<TModal>>` и тогда можно убрать поле children. Оно типизируется автоматически

2022-12-01 16:33 UTC, kyzinatra commented on src/components/orders-list/orders-list.tsx
>      if (imagesItem._id === ingredientId) {
По аналогии. Если вы указываете, что `ingredients.reduce((acc: TCartIngredient , ingredientId: string) => ... )`, то `ingredients: string[]`

2022-12-01 16:33 UTC, kyzinatra commented on src/components/orders-list/orders-list.tsx
> +  const getDate = () => Math.round((new Date().getTime() - Date.parse(orderItem.createdAt)) / 86400000 );
Можно лучше: `nowDate` не используется

2022-12-01 16:33 UTC, kyzinatra commented on src/services/types-components.ts
> +
По аналогии итд где есть any...
Их стоит типизировать так как, скорее всего, мы ожидаем в качестве переменной что-то конкретное. Если тип не понятен и береться из библиотеки, то его там можно посмотреть так как все библиотеки типихированны

2022-12-01 16:33 UTC, kyzinatra commented on src/services/middleware/socket-middleware.ts
> +          const parsedData = JSON.parse(data);
По аналогии

2022-12-01 16:33 UTC, kyzinatra commented on src/utils/utils.tsx
> +if (response.ok) return response.json();
По аналогии. Тут в качестве типа response существует встроенный тип `Response`

2022-12-01 16:33 UTC, kyzinatra commented on src/utils/utils.tsx
> +props = props || {};
В данном случае, кстати, any можно заменить на `string | number | Date` так как, как я вижу `const propValue = props[propName];` вы берете это значение 
`updatedCookie += '=' + propValue;` и тут приводите его к строке. Так что тоже без any можно

2022-12-01 16:33 UTC, kyzinatra commented on src/services/constants/index.ts
> +export const APPLY_PERSON_FAILED: 'APPLY_NEW_PERSON_FAILED' = 'APPLY_NEW_PERSON_FAILED';
Можно лучше: В таких константах ts сам сможет вывести тип. Так что тут можно его не писать

2022-12-01 16:33 UTC, kyzinatra commented on src/services/types/index.ts
> +export type AppThunk<ReturnType = void> = ActionCreator<
Отлично! Круто, что вы типизировали хуки

2022-12-01 16:33 UTC, kyzinatra commented on src/services/types/data.ts
> +  readonly success: boolean;
Можно лучше: этот тип можно вывести из TExitBody с помощью встроенных функций ts `Required<Type>` и `Readonly<Type>`

2022-12-01 18:07 UTC, trashmarket commented on src/components/burger-list/burger-list.tsx
> +  const bunRef = useRef<HTMLHeadingElement>(null);
Когда я типизирую этот реф у меня вылезает ошибка с event не знаю что с ней делать

2022-12-01 18:07 UTC, trashmarket commented on src/components/burger-list/burger-list.tsx
> +  const bunRef = useRef<HTMLHeadingElement>(null);
@kyzinatra Когда я типизирую этот реф у меня вылезает ошибка с event не знаю что с ней делать

2022-12-01 19:23 UTC, trashmarket commented on src/components/orders-list/orders-list.tsx
>      if (imagesItem._id === ingredientId) {
@kyzinatra У меня тут беда когда ingredients: string[] обозначаю тип все становится красным

2022-12-02 16:18 UTC, kyzinatra commented
Вы отлично потрудились.

Поздравляю! Ваша работа принята.
Удачного дальнейшего обучения.

2022-12-04 19:13 UTC, merged